type Tmember = {
  id: number;
  senior: string;
  current: boolean; //1-> Current; 2-> Former; 3->PhD Student
  name: string;
  category: string;
  department: string;
  group: string;
  email: string;
  orcid: string;
  scholar: string;
  website: string;
  socialmedia: string;
  imageID: string;
  description: string;
};
export const team: Tmember[] = [
  {
    id: 1,
    senior: "yes",
    current: true,
    name: "Marta Pascual Berniola",
    category: "Full Professor",
    department: "Genetics, Microbiology and Statistics",
    group: "Evolutionary Genetics Lab",
    email: "martapascual@ub.edu",
    orcid: "https://orcid.org/0000-0002-6189-0612",
    scholar: "https://scholar.google.co.uk/citations?user=dRt0zE4AAAAJ&hl=ca",
    website:
      "https://webgrec.ub.edu/webpages/000011/cat/martapascual.ub.edu.html",
    socialmedia: "",
    imageID: "martapas",
    description:
      "My research lines focus on the analysis of evolutionary processes and population genetic studies with different native and introduced taxa, including marine invertebrates and vertebrates, and a few other non-model yet ecologically very interesting species. We have analysed genetic connectivity among populations using different molecular markers and revealed the role of marine currents modifying gene flow in space and time. Adaptation is a key issue on a changing environment, and I am interested in identifying genes under selection and study their variation along geographic gradients. In laboratory and natural studies, we have shown that most changes occur within the first generations, indicating that both selection and drift act shaping the genetic makeup of populations. In the last years, I am interested in genomic techniques that we have applied to improve the knowledge of adaptation and dispersal in our endangered, commercial, invasive and ecosystem engineer species.",
  },
  {
    id: 2,
    senior: "no",
    current: true,
    name: "Helena Vela",
    category: "Estudiante de doctorado",
    department: "Genetica, Microbiologia, Estadística i IrBIO",
    group: " ",
    email: "helena.vela.garcia@gmail.com",
    orcid: "https://orcid.org/0009-0003-7746-2035",
    scholar: "https://scholar.google.com/citations?user=YdHnkqUAAAAJ&hl=en",
    website: "",
    socialmedia: "",
    imageID: "helenavel",
    description:
      "I am a marine biologist specializing in Oceanography and Marine Environmental Management, with expertise in sea turtle genetics, ecology, and conservation. My experience spans monitoring nesting females and foraging males of species like Lepidochelys olivacea, Chelonia mydas, and Eretmochelys imbricata in Costa Rica, satellite tracking Caretta caretta in Italy, and conservation work in North Cyprus, where I conducted nest excavations and tissue sampling of females and hatchlings for genomic studies. During my master’s thesis, I analyzed the origin of Caretta caretta and Chelonia mydas at a Mediterranean foraging ground. Currently, I am pursuing a PhD at the University of Barcelona, focusing on the foraging grounds of these species in the Mediterranean and Spanish Atlantic coast, employing 2bRAD genomics techniques to inform conservation efforts.",
  },
  {
    id: 3,
    senior: "no",
    current: true,
    name: "Carles Galià Camps",
    category: "Investigador postdoctoral",
    department: "Sociedad de Amigos del Museo Nacional deciencias Naturales",
    group: "",
    email: "cgaliacamps@gmail.com",
    orcid: "https://orcid.org/0000-0002-0945-0249",
    scholar: "https://scholar.google.com/citations?hl=en&user=9b_b_o0AAAAJ",
    website: "",
    socialmedia: "",
    imageID: "carlesgal",
    description:
      "I am an evolutionary marine biologist highly interested in genomics, transcriptomics, and symbiont communities. My research combines morphology, ecology, and molecular biology to understand how marine organisms evolve, speciate, adapt, and colonize new habitats. My skills include reference genome assembly and annotation, chromosomal structural variants identification, population structure analyses, adaptation signal detection, demography reconstruction, phylogeography, protein modeling, and analysis of microbiome symbiotic communities.",
  },
  {
    id: 4,
    senior:"no",
    current: true,
    name: "Gisela Marin-Capuz",
    category: "PhD Student",
    department: "Genètica, Microbiologia i Estadística",
    group: "",
    email: "giselamarincapuz@gmail.com",
    orcid: "https://orcid.org/0000-0002-4166-4685",
    scholar:
      "https://scholar.google.es/citations?view_op=list_works&hl=ca&user=RwwjbR8AAAAJ&gmla=AGd7smEqBFFVH88vqEM97UvpGQRkSTN-QgGpVohaTgvxU9AHbk8ewXAa_lyn-Ls4baQMmGdb8sSmxhALWkh96WqT_3htEVVhNFtEsD46BRvmHVAC",
    website: "",
    socialmedia: "",
    imageID: "giselamar",
    description:
      "I am an environmental biologist with a special interest in sea turtles. I have worked with these species both in the field and in the laboratory. I have worked as a research assistant in Costa Rica and Cape Verde, until I found the opportunity to work with sea turtles at home. I am currently pursuing a PhD at the Evolutionary Genetics Laboratory of the University of Barcelona. My research focuses on the genomic study of emergent nesting events of two species of sea turtles, Caretta caretta and Chelonia mydas, in the western Mediterranean. My main objectives are to understand the origin of these events, assess their viability, explore the multipaternity of the nests and conduct a census of breeding individuals. My interests also include spatial analysis and habitat modelling to understand the environmental changes that influence the evolutionary changes of these species.",
  },
  {
    id: 5,
    senior:"yes",
    current: true,
    name: "Owen S. Wangensteen",
    category: "Professor lector",
    department: "Biologia Evolutiva, Ecologia i CIències Ambientals",
    group: "Marine Biodiversity and Evolution",
    email: "owenwangensteen@gmail.com",
    orcid: "https://orcid.org/0000-0001-5593-348X",
    scholar: "https://scholar.google.es/citations?user=XRNPLjIAAAAJ",
    website: "https://sites.google.com/site/owenwangensteen",
    socialmedia: "",
    imageID: "owenwan",
    description:
      "Owen S. Wangensteen is an invertebrate zoologist, marine molecular ecologist and environmental bioinformatician, internationally recognized as an expert in the application of high-throughput sequencing data to address ecological questions in marine ecosystems. He is actively developing metabarcoding techniques for eukaryotic biodiversity assessment of marine communities and metaphylogeographical approaches to assess genomic population diversity and connectivity from marine environmental DNA.",
  },
  {
    id: 6,
    senior: "yes",
    current: true,
    name: "Cinta Pegueroles",
    category: "Professora lectora",
    department:
      "Dpt. Genètica i Microbiologia de la Universitat Autònoma de Barcelona",
    group: "",
    email: "cinta.pegueroles@gmail.com",
    orcid: "https://orcid.org/0000-0003-0701-9866",
    scholar: "https://scholar.google.com/citations?user=YlcxKEgAAAAJ&hl=es",
    website: "",
    socialmedia: "",
    imageID: "cintapeg",
    description:
      "I am a biologist specialized in genetics and bioinformatics and my main research interests are population genomics, evolution and adaptation. My overall goal is to understand how genomes evolve using large-scale data. In particular, I am interested in understanding the genetic basis of adaptation and in deciphering the functionality of long non-coding genes, as well as their role in genome evolution and adaptation. To do so, I use both an evolutionary perspective that provides information of ancient events and a population perspective that provides information about more recent events.",
  },
  {
    id: 7,
    senior: "no",
    current: true,
    name: "Ainhoa López",
    category: "PhD student",
    department: "Genetics, Microbiology and Statistics",
    group: "Evolutionary Genetics",
    email: "ainhoa14ainhoa@gmail.com",
    orcid: "0009-0006-1599-9357",
    scholar: "https://scholar.google.com/citations?hl=es&user=37txp4oAAAAJ",
    website: "",
    socialmedia:
      "Instagram: @ainhoalopezzz14; bluesky: @ainhoalopez.bsky.social",
    imageID: "ainhoalop",
    description:
      "I am a marine biologist with a background in Marine Sciences and an international master’s degree in Marine Biology. I am currently doing a PhD in genetics, where my research focuses on the genomics of marine organisms, covering both population genomics using focal and non-focal reference genomes with reduced representation techniques and whole genome sequencing. The organisms I work with are sea urchins, fish, and holothurians. ",
  },
  {
    id: 8,
    senior: "yes",
    current: true,
    name: "Carlos Carreras Huergo",
    category: "Professor Agregat",
    department: "Genètica, microbiologia i Estadistica",
    group: "Evolutionary Genetics Group",
    email: "carreras@ub.edu",
    orcid: "https://orcid.org/0000-0002-2478-6445",
    scholar: "https://scholar.google.es/citations?hl=en&user=XznszyoAAAAJ",
    website: "https://webgrec.ub.edu/webpages/000011/cat/carreras.ub.edu.html",
    socialmedia: "",
    imageID: "carloscar",
    description:
      "I am a Senior Lecturer in the Department of Genetics, Microbiology and Statistics of the University of Barcelona and member of IRBIO. My research focus on deciphering the structuring and connectivity of marine organisms and how they adapt to changing environments to understand their biology and to develop scientifically based conservation and management plans. I started working on biology, population genetics, distribution, migration and conservation of marine turtles. During the past two decades, I have been pioneering in using genetic approaches to study nesting populations and foraging grounds of different species of marine turtles worldwide, by building a strong international network of collaborations. Since 2015 I have incorporated the use of different High Throughput Sequencing genomic approaches including RAD sequencing, genome assembly and annotation, genome resequencing, microbiome analysis with amplicon sequencing and transcription analysis, also in other marine organisms including endemic fishes, sea urchins or invasive ascidians. ",
  },
  {
    id: 9,
    senior: "no",
    current: true,
    name: "Sara González-Delgado",
    category: "Postdoctoral research",
    department: "Evolutionary Biology, Ecology & Environmental Sciences ",
    group: "Adaptive Team",
    email: "saglezdel@gmail.com",
    orcid: "https://orcid.org/0000-0001-8715-7411",
    scholar: "https://scholar.google.com/citations?user=0GB6dpIAAAAJ&hl=es",
    website: "",
    socialmedia: "",
    imageID: "saragon",
    description:
      "Postdoctoral researcher at the University of Barcelona, specializing in molecular ecology and the impact of climate change on marine ecosystems. She holds a BSc and MSc from the University of La Laguna, where she studied global warming and ocean acidification effects on marine invertebrates. Her PhD focused on the diversity of benthic communities and echinoderm adaptations to naturally acidified environments. Her expertise includes oceanographic chemistry, metabarcoding, and population genomics. Since 2018, she has coordinated research at the Marine Observatory of Climate Change (OMACC). Currently, her work explores the trophic interactions of two sea urchin species in naturally acidified ecosystems, integrating stable isotope analysis and DNA metabarcoding to understand long-term ecological changes.",
  },
  {
    id: 10,
    senior: "yes",
    current: true,
    name: "Francesc Mestres",
    category: "Catedrático de Universidad",
    department: "Genética, Microbiología y Estadística",
    group: "Genètica evolutiva",
    email: "fmestres@ub.edu",
    orcid: "https://orcid.org/0000-0002-9073-4862 ",
    scholar:
      "https://scholar.google.com/citations?hl=es&user=lnbGPyIAAAAJ&view_op=list_works&sortby=pubdate",
    website: "https://webgrec.ub.edu/webpages/000011/cat/fmestres.ub.edu.html",
    socialmedia: "",
    imageID: "francescmes",
    description:
      "Me licencié en Ciencias Biológicas (1982) y posteriormente fui Doctor en dicha especialidad (1988), en ambos casos por la Universitat de Barcelona. Estoy vinculado académicamente con dicha institución desde 1985, siendo Catedrático de Universidad (área Genética) desde 2020. Mi especialidad es la Genética de Poblaciones y Evolutiva, trabajando en temas tales como la colonización de nuevos hábitats y la adaptación al cambio climático, utilizando diferentes especies de drosofílidos y de cangrejos marinos. Actualmente imparto las asignaturas siguientes: Biología, Genética: análisis genético, Evolución y Genética forense. He obtenido seis Distinciones Docentes de la Facultat de Biologia (U.B.) y estoy en posesión de la Medalla de Bronce al Mérito Policial con distintivo azul (CME-Policía de Catalunya).",
  },
  {
    id: 11,
    senior: "yes",
    current: true,
    name: "Manuel Ballesteros",
    category: "Emeritus Professor",
    department: "Biologia Evolutiva, Ecologia i Ciències Ambientals",
    group: "Marine invertebrate biodiversity",
    email: "glaucusmb@gmail.com",
    orcid: "0000-0001-9055-1241",
    scholar: "https://scholar.google.es/citations?user=ckYjnKUAAAAJ&hl=en",
    website: "http://opistobranquis.info/en/",
    socialmedia: "",
    imageID: "manuelbal",
    description:
      "Graduated in Biology from the University of Barcelona in 1975 and PhD in Biology from the same university in 1980. Professor of Zoology at the University of Barcelona since 1983, teaching subjects in General Zoology, Invertebrates, Marine Zoology, Biology of Marine Invertebrates, Fisheries, Biology of animal species of commercial interest, Polar Oceans, Applied Zoology, among others. Specialist in the biodiversity of marine invertebrates and especially opisthobranch mollusks (Gastropoda, Heterobranchia) with more than 100 published scientific articles and some more of an informative nature. Has carried out numerous national and international research campaigns in different oceans and attended more than 50 national and international congresses or symposia. CMAS *** star sports diver, with more than 1,500 dives in the Mediterranean, Caribbean, Atlantic, Red Sea, Indian Ocean, Pacific and Antarctica. Expert in underwater photography and video. Retired since November 2022 and with the title of Emeritus Professor since October 2023.",
  },
  {
    id: 12,
    senior: "no",
    current: true,
    name: "Alessia Cherin",
    category: "PhD student",
    department: "Department of Genetics, Microbiology and Statistics",
    group: "Evolutionary Genetics Lab",
    email: " cherinalessia98@gmail.com",
    orcid: "0000-0003-4680-6352",
    scholar:
      "https://scholar.google.es/citations?view_op=list_works&hl=it&user=RlKRLwQAAAAJ",
    website: "",
    socialmedia: "@cherinsss (instagram)",
    imageID: "alessiache",
    description:
      "I obtained my Bachelor's degree in Biological Sciences from the University of Florence, followed by a Master's degree in Marine Biology from the University of Genoa. Currently, I am pursuing a PhD focusing on population genomics of sea turtles, specifically Caretta caretta, Dermochelys coriacea, and Chelonia mydas. My research aims to enhance our understanding of genetic diversity and population structure in these species, contributing to their conservation and management.",
  },
  {
    id: 13,
    senior: "no",
    current: true,
    name: "Vanessa Arranz",
    category: "Postdoctoral researcher",
    department: "Evolutionary biology, ecology and environmental sciences",
    group: "Adaptive team",
    email: "vanearranz7@gmail.com",
    orcid: "https://orcid.org/0000-0002-3404-5317",
    scholar: "https://scholar.google.com/citations?user=-1eos5cAAAAJ&hl=en",
    website: "https://echinoadaptive.wixsite.com/adaptive-team",
    socialmedia: "",
    imageID: "vanessaarr",
    description:
      "I am a Marie Skłodowska-Curie Postdoctoral researcher, specialized in marine biology, molecular ecology, genetics, and bioinformatics. My research aims to elucidate the ecology, diversity, and distribution of marine organisms. Utilizing approaches ranging from single-species studies to comprehensive multi-species assessments, I investigated genetic connectivity among marine populations. Currently, I am focused on the adaptation of organisms to climate change, particularly examining ocean acidification along natural gradients. By integrating advanced molecular methods such as transcriptomics (RNAseq), DNA metabarcoding and microbiome analysis, with field studies, my research provides insights into how marine species adjust to environmental stressors, enhancing our understanding of evolutionary processes and informing effective conservation strategies. My interdisciplinary approach bridges molecular techniques with ecological fieldwork, offering contributions to study of climate adaptation. ",
  },
  {
    id: 14,
    senior: "no",
    current: true,
    name: "Liam Junkin Royo",
    category: "PhD Student",
    department: "Gentics, Microbiology and Statistics",
    group: "Evolutionary Genetics",
    email: "liam.junkin@gmail.com",
    orcid: "https://orcid.org/0009-0006-7678-9337",
    scholar:
      "https://scholar.google.es/citations?view_op=list_works&hl=en&user=xZ33otQAAAAJ",
    website: "",
    socialmedia: "Bluesky: junkinroyo.bsky.social",
    imageID: "liamjun",
    description:
      "I  am a marine biologist with a degree in marine sciences and a master’s degree in biodiversity. My research focuses on applying whole genome sequencing techniques to investigate the evolutionary relationships and invasion pathways of ascidians. My background includes studying the seasonal diversity of microbial communities inhabiting invasive ascidians and utilizing bioinformatics tools to analyze the population genetic structure of gutless oligochaetes and their symbiotic microbial partners. ",
  },
  {
    id: 15,
    senior: "no",
    current: true,
    name: "Aitana Merino",
    category: "PhD Student",
    department: "Department of Genetics, Microbiology and Statistics",
    group: "Evolutionary Genetics Lab",
    email: "     aitanameri@gmail.com",
    orcid: "https://orcid.org/0009-0000-5937-2819",
    scholar:
      "https://scholar.google.es/citations?view_op=list_works&hl=es&user=Pp7ie7cAAAAJ&gmla=AOv-ny9xwCSiAxoadH38LpB1MxFbZ7kuWGNiUjVgaDW9FSMpFBXI2s0K4SKQAatpg3MsY3N05P-ibvlYBq8dAq2pMI_YRiVOtMZubq9aSukIedzZi2TmXQ2b_gh56CPCphLUog8",
    website: "",
    socialmedia: "",
    imageID: "aitanamer",
    description:
      "I am a biologist who graduated from the University of the Basque Country (UPV-EHU) and specialised in Biodiversity and Evolutionary Biology at the University of Barcelona (UB). Currently, I am a PhD student at the same institution. My research aims to address the reasons behind the recent colonization of the western Mediterranean by the loggerhead turtle (Caretta caretta) through a combination of genomic, geometric morphometry, and stable isotope analysis techniques. To achieve this, my first objective is to assess the number of breeding individuals and the connectivity among nesting regions. Secondly, I aim to identify the origin of the colonization events and the foraging grounds of the nesting females. Finally, I will cross-reference this information to evaluate the impact of female foraging strategies and the origin of the colonizers on nesting reproductive parameters.",
  },
  {
    id: 16,
    senior: "no",
    current: true,
    name: "Robert Fernandez Vilert",
    category: "PhD student",
    department: "BEECA",
    group: "Rocío Pérez Portela - Adaptive team",
    email: "     r.fvilert@gmail.com",
    orcid: "https://orcid.org/my-orcid?orcid=0000-0002-2812-4414",
    scholar:
      "https://scholar.google.es/citations?user=dVED18oAAAAJ&hl=es&oi=sra",
    website: "",
    socialmedia: "@rob.fernandz",
    imageID: "robertfer",
    description:
      "Trying to understand the biological buffer systems of marine invertebrates that calcify to cope with the rapid environmental changes expected in the predicted global ocean acidification and warming scenario by applying genomics, transcriptomics, and metagenomics, along with metabolic ecology.",
  },
  {
    id: 17,
    senior: "no",
    current: true,
    name: "Andrea Prófumo",
    category: "PhD student",
    department: "BEECA",
    group: "Conxita's Lab",
    email: "ae.profumo@gmail.com",
    orcid: "https://orcid.org/0000-0001-8163-1661",
    scholar:
      "https://scholar.google.es/citations?user=Udp-josAAAAJ&hl=es&oi=sra",
    website: "",
    socialmedia: "@andprofumo",
    imageID: "andreapro",
    description:
      "PhD candidate in Marine Sciences at the Universitat de Barcelona (UB), supported by an FPI fellowship from the Agencia Estatal de Investigación (AEI) and the Ministerio de Ciencia, Innovación y Universidades (MICIU). She is also affiliated with the Institut de Recerca de la Biodiversitat (IRBio). She earned a degree in Biological Systems Engineering from the Universitat Politècnica de Catalunya (UPC) and a Master’s in Oceanography and Marine Environment Management from UB, graduating with distinction for her thesis. Prófumo has completed different researchs at the Institute of Marine Sciences (ICM-CSIC), the Institute for Research and Technology in Food and Agriculture (IRTA), the Universidad de Concepción (UdeC, Chile), and the Istituto di Chimica Biomolecolare (ICB-CNR, Italy). Her research interests include marine sciences, climate change, marine natural products, and the population genetics of Antarctic marine invertebrates. Prófumo is committed to advancing knowledge on the environmental impacts of climate change on Antarctic marine biodiversity and fostering sustainable marine ecosystem management.",
  },
  {
    id: 18,
    senior: "no",
    current: true,
    name: "Pere Monràs i Riera",
    category: "Predoctoral researcher",
    department: "BEECA",
    group: "Biologia i Ecologia Bentòniques",
    email: "pmonrasriera@gmail.com",
    orcid: "https://orcid.org/0000-0002-9438-1662",
    scholar:
      "https://scholar.google.com/citations?user=jAMoycYAAAAJ&hl=ca&oi=ao",
    website:
      "https://www.researchgate.net/profile/Pere-Monras-Riera-3?ev=hdr_xprf",
    socialmedia: "www.linkedin.com/in/pere-monràs-i-riera-6258a914b",
    imageID: "peremon",
    description:
      "Driven by a deep fascination for the ocean and a passion for protecting our planet, I am dedicated to understanding and improving marine health. As a biologist specialising in Ecology, Management, and Restoration of the Natural Environment, I am pursuing a PhD focused on marine debris in Antarctica. My research explores its abundance, sources, and the microorganisms colonising plastics, aiming to contribute to the conservation of this unique and fragile ecosystem.",
  },
];
